v0.1.62 - @track only appears to work from the main application - problem exists in __init__.py witin db() variable relying on os.getcwd()